version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin <account-no>.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t arete_backend .
      - docker tag arete_backend:latest <account-no>.dkr.ecr.us-east-1.amazonaws.com/arete_backend:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push <account-no>.dkr.ecr.us-east-1.amazonaws.com/arete_backend:latest